server:
  port: 8000
  mode: dev
mysql:
  host: localhost
  port: 3306
  user: root
  password: root1234
  dbname: user_db
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600
logger:
  level: debug
  file_name: "./storage/logs/app.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true